--532147
/** For CR or data table structure revise

DECLARE @VERSION NVARCHAR(6) = '2016Q4'	

ALTER TABLE fact.ABC_DATA_CENTER_HISTORY
ADD [Total E2E Matl Cost] float null,
    [Total E2E Matl - Inv Cost] float null

ALTER TABLE fact.ABC_DATA_CENTER_HISTORY
ADD [Non Event Cost] FLOAT NULL

UPDATE AA
SET AA.[Total E2E Matl Cost] = BB.[Total E2E Matl Cost],
    AA.[Total E2E Matl - Inv Cost] = BB.[Total E2E Matl - Inv Cost]
FROM fact.ABC_DATA_CENTER_HISTORY AA, [staging].[ABC_S3_LINK_SUPPLIER] BB
WHERE AA.[Unique Link Key] = BB.[Unique Link Key]


**/

DECLARE @VERSION NVARCHAR(6) = '2017Q2'	

DELETE FROM [fact].[ABC_DATA_CENTER_HISTORY]
WHERE [Data Period] = @VERSION

INSERT INTO [fact].[ABC_DATA_CENTER_HISTORY](
       [Data Period]
      ,[Unique Link Key]
      ,[Master Event Activity Month]
      ,[Source System]
      ,[Region]
      ,[Master Event Number]
      ,[Event Number]
      ,[Event Country Iso Cd]
      ,[Part Qty Demanded]
      ,[Event Hwpl]
      ,[Part Number]
      ,[Part Actual SL]
      ,[Part Shipment Month]
      ,[Part Qty Consumed]
      ,[So + Item]
      ,[GSD SC DMR Flag]
      ,[Event SPL]
      ,[Sc SPL]
      ,[Part SPL]
      ,[Part SPL Desc]
      ,[Part Commodity]
      ,[Part Description]
      ,[Safari Warranty Flag]
      ,[L2 Reverse Unique Link Key]
      ,[Received Month]
      ,[Phy Part No Rec Date]
      ,[Flow Tag]
      ,[Actual Disposition]
      ,[Notification Type A]
      ,[Receipt Type]
      ,[CT Code Label]
      ,[MFG Date]
      ,[Part Age]
      ,[Received Part Kit Part Number]
      ,[Physical Part Number]
      ,[Part Qty Received]
      ,[Received Plant]
      ,[Match FL]
      ,[SN Transaction Status]
      ,[Sales Doc Type]
      ,[Sales Document]
      ,[Qspeak Vendor]
      ,[Qspeak Flowtag]
      ,[Qspeak Flowtag Used]
      ,[Qspeak OEM Name]
      ,[Qspeak Disposition]
      ,[Qspeak Warranty Status]
      ,[Qspeak Upload Date]
      ,[Qspeak Upload Month]
      ,[Qspeak TAT]
      ,[iReturn Received Plant]
      ,[iReturn Disposition]
      ,[iReturn Report Month]
      ,[iReturn Vendor ID]
      ,[iReturn Vendor Name]
      ,[APJ Received Plant]
      ,[APJ Disposition]
      ,[RWT CID]
      ,[RWT Credit]
      ,[RWT Disposition]
      ,[RWT Vendor ID]
      ,[RWT Vendor Name]
      ,[RWT Engineer Approval]
      ,[RWT NFF Results]
      ,[RWT Release Month]
      ,[L1 Supplier]
      ,[L1 Supplier Source]
      ,[L2 Supplier]
      ,[Supplier Type]
      ,[Final Disp Flag]
      ,[Cons Cost]
      ,[DI Cost]
      ,[DI Credit]
      ,[OOW Avg Repair Cost]
      ,[OOW/IW Avg Repair Cost]
      ,[Is Avg RC GT RVS]
      ,[Cons Cost Notes]
      ,[ESC Variance]
      ,[Def Scrap Cost]
      ,[NPPO Cost]
      ,[Event PN RVS]
      ,[Event PN NRS]
      ,[Received Part Kit PN RVS]
      ,[Physical PN RVS]
      ,[Physical PN NRS]
      ,[Physical PN NBS]
      ,[Relabel Cost]
      ,[Dekit Cost]
      ,[Relabel Cost Comment]
      ,[Dekit Cost Comment]
      ,[Credits]
      ,[Credit Comments]
      ,[Cons Cost at Std]
      ,[Country Inv Costs]
      ,[Region Inv Costs]
      ,[Total Inv Costs]
	  ,[Total E2E Matl Cost]
	  ,[Total E2E Matl - Inv Cost]
      ,[Taxes]
	  ,[Non Event Cost]
)
SELECT @VERSION as [Data Period]
      ,[Unique Link Key]
      ,[Master Event Activity Month]
      ,[Source System]
      ,[Region]
      ,[Master Event Number]
      ,[Event Number]
      ,[Event Country Iso Cd]
      ,[Part Qty Demanded]
      ,[Event Hwpl]
      ,[Part Number]
      ,[Part Actual SL]
      ,[Part Shipment Month]
      ,[Part Qty Consumed]
      ,[So + Item]
      ,[GSD SC DMR Flag]
      ,[Event SPL]
      ,[Sc SPL]
      ,[Part SPL]
      ,[Part SPL Desc]
      ,[Part Commodity]
      ,[Part Description]
      ,[Safari Warranty Flag]
      ,[L2 Reverse Unique Link Key]
      ,[Received Month]
      ,[Phy Part No Rec Date]
      ,[Flow Tag]
      ,[Actual Disposition]
      ,[Notification Type A]
      ,[Receipt Type]
      ,[CT Code Label]
      ,[MFG Date]
      ,[Part Age]
      ,[Received Part Kit Part Number]
      ,[Physical Part Number]
      ,[Part Qty Received]
      ,[Received Plant]
      ,[Match FL]
      ,[SN Transaction Status]
      ,[Sales Doc Type]
      ,[Sales Document]
      ,[Qspeak Vendor]
      ,[Qspeak Flowtag]
      ,[Qspeak Flowtag Used]
      ,[Qspeak OEM Name]
      ,[Qspeak Disposition]
      ,[Qspeak Warranty Status]
      ,[Qspeak Upload Date]
      ,[Qspeak Upload Month]
      ,[Qspeak TAT]
      ,[iReturn Received Plant]
      ,[iReturn Disposition]
      ,[iReturn Report Month]
      ,[iReturn Vendor ID]
      ,[iReturn Vendor Name]
      ,[APJ Received Plant]
      ,[APJ Disposition]
      ,CONVERT(VARCHAR(50),[RWT CID])
      ,[RWT Credit]
      ,CONVERT(VARCHAR(50),[RWT Disposition])
      ,CONVERT(VARCHAR(50),[RWT Vendor ID])
      ,CONVERT(VARCHAR(50),[RWT Vendor Name])
      ,CONVERT(VARCHAR(50),[RWT Engineer Approval])
      ,CONVERT(VARCHAR(50),[RWT NFF Results])
      ,CONVERT(VARCHAR(50),[RWT Release Month])
      ,[L1 Supplier]
      ,[L1 Supplier Source]
      ,[L2 Supplier]
      ,[Supplier Type]
      ,[Final Disp Flag]
      ,[Cons Cost]
      ,[DI Cost]
      ,[DI Credit]
      ,[OOW Avg Repair Cost]
      ,[OOW/IW Avg Repair Cost]
      ,[Is Avg RC GT RVS]
      ,[Cons Cost Notes]
      ,[ESC Variance]
      ,[Def Scrap Cost]
      ,[NPPO Cost]
      ,[Event PN RVS]
      ,[Event PN NRS]
      ,[Received Part Kit PN RVS]
      ,[Physical PN RVS]
      ,[Physical PN NRS]
      ,[Physical PN NBS]
      ,[Relabel Cost]
      ,[Dekit Cost]
      ,[Relabel Cost Comment]
      ,[Dekit Cost Comment]
      ,[Credits]
      ,[Credit Comments]
      ,[Cons Cost at Std]
      ,[Country Inv Costs]
      ,[Region Inv Costs]
      ,[Total Inv Costs]
	  ,[Total E2E Matl Cost]
	  ,[Total E2E Matl - Inv Cost]
      ,[Taxes]
	  ,[Non Event Cost]
FROM [staging].[ABC_S3_LINK_SUPPLIER]

